### ISSUE TITLE
Atoms packages not installed

### ISSUE THREAD

**Issue by JuanObiJuan** [unity-atoms/unity-atoms-examples#6]
Opening this project in Unity 2021 ends with "com.mambojambostudios.marvelous" as the only external dependcy package.

This issue bring also the question if Its good idea to include in this atom-exmaples project other external dependencies than the atoms packages.

**Comment by AdamRamberg** [comment]
The `unity-atoms` repo is included as a submodule in this repo, so you need to pull the submodule in order to make the project run. 

I believe that other dependencies are fine to include. The idea going forward though is to convert the main repo (`unity-atoms`) to be a Unity project and to include these examples. 

Will close this issue since I don't think the issue still is relevant. Let me know if you disagree.
